#!/bin/sh

# Stash unstaged changes
git stash -k -u -q

# Run the resume generator script
python3 "$(git rev-parse --show-toplevel || true)/generator.py" "--release"

# Check the exit status of the script
if [ $? -ne 0 ]; then
	echo "Pre-commit hook failed. Please fix the issues before committing."
	# Restore the stashed changes
	git stash pop -q
	exit 1
fi

# Add the resultant files
git add docs/Jonathan_Hendrickson_resume.pdf
git add docs/index.html

# Restore the stashed changes
git stash pop -q

exit 0
